Traceback (most recent call last):
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\BEGAS_15\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\BEGAS_15\PycharmProjects\geospatial_analysis\venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import shapely.geometry as geom

# Ï†ê Í∞úÏ≤¥ ÏÉùÏÑ±
point1 = geom.Point(24.952242, 60.1696017)
point2 = geom.Point(24.976567, 60.1612500)

# Îã§Í∞ÅÌòï Í∞úÏ≤¥ ÏÉùÏÑ±
polygon = geom.Polygon([(24.950899, 60.169158),
                        (24.953492, 60.169158),
                        (24.953510, 60.170104),
                        (24.950958, 60.169990)
                       ])

print(point1)
print(point2)
print(polygon)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mshapely[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgeometry[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgeom[39;00m
[0;32m      3[0m [38;5;66;03m# Ï†ê Í∞úÏ≤¥ ÏÉùÏÑ±[39;00m
[0;32m      4[0m point1 [38;5;241m=[39m geom[38;5;241m.[39mPoint([38;5;241m24.952242[39m, [38;5;241m60.1696017[39m)

[1;31mModuleNotFoundError[0m: No module named 'shapely'

